### ISSUE TITLE
Say where an non-existing ideology is referenced

### ISSUE THREAD

**Issue by DrDiHai** [KR4/HOI4-Validator#3]
Like this vanillla error message:
[21:34:45][triggerimplementation.cpp:3800]: Wrong ideology: Error in trigger:has_government
but say where it occurs.

**Comment by DrDiHai** [comment]
Well, that's true. But we would still want to know whne we make a mistake. Actually, these vanilla errors would only show up if we verify the vanilla files, though.

**Comment by karrot1** [comment]
Done! Btw, non-existing ideologies are referenced in \common\national_focus\KR_Chile.txt on lines 2013, 2150, and 2301. All of these are capitalization errors. (Social_Liberal instead of social_liberal) No-one told me if capitalization matters or not so I'm assuming that it does.
