### ISSUE TITLE
Check that all 3 Flag Graphics (Large Medium Small) exist for a given tag or cosmetic tag

### ISSUE THREAD

**Issue by Delincious** [KR4/HOI4-Validator#78]
The game does not check that flags in mod\Kaiserreich\gfx\flags exist for all 3 sizes of flag graphic, large, medium, and small. This causes some small graphical problems if not all 3 sizes exist.

Note that a cosmetic tag does not necessarily need a flag, but if one size exists, all 3 sizes should exist.

**Comment by karrot1** [comment]
Solved. It turns out Menguko and Lebanon don't have medium flags. Did you know Menguko and Lebanon were in Kaiserreich? I didn't, but it seems like they are.
