### ISSUE TITLE
Check for non-existent states in focus trees, decisions, and events

### ISSUE THREAD

**Issue by snoekbaars** [KR4/HOI4-Validator#82]
If a state that doesn't exist is in a focus tree, decision or event, firing or hovering over it will crash the game. This error is not shown in the hoi4 error log.

**Comment by karrot1** [comment]
Added, assuming the places state ids will be referenced are 'add_state_claim = ', 'owns_state = ', 'controls_state = ', 'transfer_state = ', 'add_state_core = ', 'state = ', and nothing else. (If there are other things that reference state ids, please tell me.)
