### ISSUE TITLE
Options menu

### ISSUE THREAD

**Issue by Zankoas** [KR4/HOI4-Validator#9]
Let people enable only certain scans

**Comment by roparex** [comment]
That's not hard 2 do but you need to be more specific of how exactly this should function. You want every scan to be optional? (and create command line arguments for every one?) Or directory-based? (Which means all scripts will have to be separated by directories they check, for example the GFX one that currently will check all GFX in the game, or the WTT land commander one that checks in national focuses, country history, events and triggered actions files/folders). 
Please be more specific.

**Comment by Zankoas** [comment]
I was thinking have a text file that is read, listing all the things it can scan for along with if it should be scanned for:

		# Check for leaders being deleted that don't exist
		leader_missing_delete = yes

**Comment by Zankoas** [comment]
Would help people know what each error means, let them save options and be user friendly

**Comment by karrot1** [comment]
Done.
